//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharmacufrom.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name suppliername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertsupplierWeb", ReplyAction="*")]
        pharmacufrom.ServiceReference2.InsertsupplierWebResponse InsertsupplierWeb(pharmacufrom.ServiceReference2.InsertsupplierWebRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertsupplierWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<pharmacufrom.ServiceReference2.InsertsupplierWebResponse> InsertsupplierWebAsync(pharmacufrom.ServiceReference2.InsertsupplierWebRequest request);
        
        // CODEGEN: Generating message contract since element name Drug_name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertdrugWeb", ReplyAction="*")]
        pharmacufrom.ServiceReference2.InsertdrugWebResponse InsertdrugWeb(pharmacufrom.ServiceReference2.InsertdrugWebRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertdrugWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<pharmacufrom.ServiceReference2.InsertdrugWebResponse> InsertdrugWebAsync(pharmacufrom.ServiceReference2.InsertdrugWebRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertinventoryWeb", ReplyAction="*")]
        int InsertinventoryWeb(int Drug_id, int Quantity_in_stock, int Unit_price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertinventoryWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertinventoryWebAsync(int Drug_id, int Quantity_in_stock, int Unit_price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertorderWeb", ReplyAction="*")]
        int InsertorderWeb(int Drug_id, int Pharmacy_ID, int Quantity, int Unit_Price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertorderWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertorderWebAsync(int Drug_id, int Pharmacy_ID, int Quantity, int Unit_Price);
        
        // CODEGEN: Generating message contract since element name Quatation_Date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertQuatationWeb", ReplyAction="*")]
        pharmacufrom.ServiceReference2.InsertQuatationWebResponse InsertQuatationWeb(pharmacufrom.ServiceReference2.InsertQuatationWebRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertQuatationWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<pharmacufrom.ServiceReference2.InsertQuatationWebResponse> InsertQuatationWebAsync(pharmacufrom.ServiceReference2.InsertQuatationWebRequest request);
        
        // CODEGEN: Generating message contract since element name Drug_name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertquatationDetailWeb", ReplyAction="*")]
        pharmacufrom.ServiceReference2.InsertquatationDetailWebResponse InsertquatationDetailWeb(pharmacufrom.ServiceReference2.InsertquatationDetailWebRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertquatationDetailWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<pharmacufrom.ServiceReference2.InsertquatationDetailWebResponse> InsertquatationDetailWebAsync(pharmacufrom.ServiceReference2.InsertquatationDetailWebRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertsupplierWebRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertsupplierWeb", Namespace="http://tempuri.org/", Order=0)]
        public pharmacufrom.ServiceReference2.InsertsupplierWebRequestBody Body;
        
        public InsertsupplierWebRequest() {
        }
        
        public InsertsupplierWebRequest(pharmacufrom.ServiceReference2.InsertsupplierWebRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertsupplierWebRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string suppliername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Supplieraddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Supplieremail;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Suppliercontact_number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Supplierregistration_date;
        
        public InsertsupplierWebRequestBody() {
        }
        
        public InsertsupplierWebRequestBody(string suppliername, string Supplieraddress, string Supplieremail, int Suppliercontact_number, string Supplierregistration_date) {
            this.suppliername = suppliername;
            this.Supplieraddress = Supplieraddress;
            this.Supplieremail = Supplieremail;
            this.Suppliercontact_number = Suppliercontact_number;
            this.Supplierregistration_date = Supplierregistration_date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertsupplierWebResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertsupplierWebResponse", Namespace="http://tempuri.org/", Order=0)]
        public pharmacufrom.ServiceReference2.InsertsupplierWebResponseBody Body;
        
        public InsertsupplierWebResponse() {
        }
        
        public InsertsupplierWebResponse(pharmacufrom.ServiceReference2.InsertsupplierWebResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertsupplierWebResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertsupplierWebResult;
        
        public InsertsupplierWebResponseBody() {
        }
        
        public InsertsupplierWebResponseBody(int InsertsupplierWebResult) {
            this.InsertsupplierWebResult = InsertsupplierWebResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertdrugWebRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertdrugWeb", Namespace="http://tempuri.org/", Order=0)]
        public pharmacufrom.ServiceReference2.InsertdrugWebRequestBody Body;
        
        public InsertdrugWebRequest() {
        }
        
        public InsertdrugWebRequest(pharmacufrom.ServiceReference2.InsertdrugWebRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertdrugWebRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Drug_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Drug_price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Drug_status;
        
        public InsertdrugWebRequestBody() {
        }
        
        public InsertdrugWebRequestBody(string Drug_name, string Description, int Drug_price, string Drug_status) {
            this.Drug_name = Drug_name;
            this.Description = Description;
            this.Drug_price = Drug_price;
            this.Drug_status = Drug_status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertdrugWebResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertdrugWebResponse", Namespace="http://tempuri.org/", Order=0)]
        public pharmacufrom.ServiceReference2.InsertdrugWebResponseBody Body;
        
        public InsertdrugWebResponse() {
        }
        
        public InsertdrugWebResponse(pharmacufrom.ServiceReference2.InsertdrugWebResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertdrugWebResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertdrugWebResult;
        
        public InsertdrugWebResponseBody() {
        }
        
        public InsertdrugWebResponseBody(int InsertdrugWebResult) {
            this.InsertdrugWebResult = InsertdrugWebResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertQuatationWebRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertQuatationWeb", Namespace="http://tempuri.org/", Order=0)]
        public pharmacufrom.ServiceReference2.InsertQuatationWebRequestBody Body;
        
        public InsertQuatationWebRequest() {
        }
        
        public InsertQuatationWebRequest(pharmacufrom.ServiceReference2.InsertQuatationWebRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertQuatationWebRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Quatation_Date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Suppliername;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int supplierid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Status;
        
        public InsertQuatationWebRequestBody() {
        }
        
        public InsertQuatationWebRequestBody(string Quatation_Date, string Suppliername, int supplierid, string Status) {
            this.Quatation_Date = Quatation_Date;
            this.Suppliername = Suppliername;
            this.supplierid = supplierid;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertQuatationWebResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertQuatationWebResponse", Namespace="http://tempuri.org/", Order=0)]
        public pharmacufrom.ServiceReference2.InsertQuatationWebResponseBody Body;
        
        public InsertQuatationWebResponse() {
        }
        
        public InsertQuatationWebResponse(pharmacufrom.ServiceReference2.InsertQuatationWebResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertQuatationWebResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertQuatationWebResult;
        
        public InsertQuatationWebResponseBody() {
        }
        
        public InsertQuatationWebResponseBody(int InsertQuatationWebResult) {
            this.InsertQuatationWebResult = InsertQuatationWebResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertquatationDetailWebRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertquatationDetailWeb", Namespace="http://tempuri.org/", Order=0)]
        public pharmacufrom.ServiceReference2.InsertquatationDetailWebRequestBody Body;
        
        public InsertquatationDetailWebRequest() {
        }
        
        public InsertquatationDetailWebRequest(pharmacufrom.ServiceReference2.InsertquatationDetailWebRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertquatationDetailWebRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Drug_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Quatation_Quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Quatation_Unit_Price;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Quatation_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Drug_name;
        
        public InsertquatationDetailWebRequestBody() {
        }
        
        public InsertquatationDetailWebRequestBody(int Drug_id, int Quatation_Quantity, int Quatation_Unit_Price, int Quatation_ID, string Drug_name) {
            this.Drug_id = Drug_id;
            this.Quatation_Quantity = Quatation_Quantity;
            this.Quatation_Unit_Price = Quatation_Unit_Price;
            this.Quatation_ID = Quatation_ID;
            this.Drug_name = Drug_name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertquatationDetailWebResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertquatationDetailWebResponse", Namespace="http://tempuri.org/", Order=0)]
        public pharmacufrom.ServiceReference2.InsertquatationDetailWebResponseBody Body;
        
        public InsertquatationDetailWebResponse() {
        }
        
        public InsertquatationDetailWebResponse(pharmacufrom.ServiceReference2.InsertquatationDetailWebResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertquatationDetailWebResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertquatationDetailWebResult;
        
        public InsertquatationDetailWebResponseBody() {
        }
        
        public InsertquatationDetailWebResponseBody(int InsertquatationDetailWebResult) {
            this.InsertquatationDetailWebResult = InsertquatationDetailWebResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : pharmacufrom.ServiceReference2.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<pharmacufrom.ServiceReference2.WebService1Soap>, pharmacufrom.ServiceReference2.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pharmacufrom.ServiceReference2.InsertsupplierWebResponse pharmacufrom.ServiceReference2.WebService1Soap.InsertsupplierWeb(pharmacufrom.ServiceReference2.InsertsupplierWebRequest request) {
            return base.Channel.InsertsupplierWeb(request);
        }
        
        public int InsertsupplierWeb(string suppliername, string Supplieraddress, string Supplieremail, int Suppliercontact_number, string Supplierregistration_date) {
            pharmacufrom.ServiceReference2.InsertsupplierWebRequest inValue = new pharmacufrom.ServiceReference2.InsertsupplierWebRequest();
            inValue.Body = new pharmacufrom.ServiceReference2.InsertsupplierWebRequestBody();
            inValue.Body.suppliername = suppliername;
            inValue.Body.Supplieraddress = Supplieraddress;
            inValue.Body.Supplieremail = Supplieremail;
            inValue.Body.Suppliercontact_number = Suppliercontact_number;
            inValue.Body.Supplierregistration_date = Supplierregistration_date;
            pharmacufrom.ServiceReference2.InsertsupplierWebResponse retVal = ((pharmacufrom.ServiceReference2.WebService1Soap)(this)).InsertsupplierWeb(inValue);
            return retVal.Body.InsertsupplierWebResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pharmacufrom.ServiceReference2.InsertsupplierWebResponse> pharmacufrom.ServiceReference2.WebService1Soap.InsertsupplierWebAsync(pharmacufrom.ServiceReference2.InsertsupplierWebRequest request) {
            return base.Channel.InsertsupplierWebAsync(request);
        }
        
        public System.Threading.Tasks.Task<pharmacufrom.ServiceReference2.InsertsupplierWebResponse> InsertsupplierWebAsync(string suppliername, string Supplieraddress, string Supplieremail, int Suppliercontact_number, string Supplierregistration_date) {
            pharmacufrom.ServiceReference2.InsertsupplierWebRequest inValue = new pharmacufrom.ServiceReference2.InsertsupplierWebRequest();
            inValue.Body = new pharmacufrom.ServiceReference2.InsertsupplierWebRequestBody();
            inValue.Body.suppliername = suppliername;
            inValue.Body.Supplieraddress = Supplieraddress;
            inValue.Body.Supplieremail = Supplieremail;
            inValue.Body.Suppliercontact_number = Suppliercontact_number;
            inValue.Body.Supplierregistration_date = Supplierregistration_date;
            return ((pharmacufrom.ServiceReference2.WebService1Soap)(this)).InsertsupplierWebAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pharmacufrom.ServiceReference2.InsertdrugWebResponse pharmacufrom.ServiceReference2.WebService1Soap.InsertdrugWeb(pharmacufrom.ServiceReference2.InsertdrugWebRequest request) {
            return base.Channel.InsertdrugWeb(request);
        }
        
        public int InsertdrugWeb(string Drug_name, string Description, int Drug_price, string Drug_status) {
            pharmacufrom.ServiceReference2.InsertdrugWebRequest inValue = new pharmacufrom.ServiceReference2.InsertdrugWebRequest();
            inValue.Body = new pharmacufrom.ServiceReference2.InsertdrugWebRequestBody();
            inValue.Body.Drug_name = Drug_name;
            inValue.Body.Description = Description;
            inValue.Body.Drug_price = Drug_price;
            inValue.Body.Drug_status = Drug_status;
            pharmacufrom.ServiceReference2.InsertdrugWebResponse retVal = ((pharmacufrom.ServiceReference2.WebService1Soap)(this)).InsertdrugWeb(inValue);
            return retVal.Body.InsertdrugWebResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pharmacufrom.ServiceReference2.InsertdrugWebResponse> pharmacufrom.ServiceReference2.WebService1Soap.InsertdrugWebAsync(pharmacufrom.ServiceReference2.InsertdrugWebRequest request) {
            return base.Channel.InsertdrugWebAsync(request);
        }
        
        public System.Threading.Tasks.Task<pharmacufrom.ServiceReference2.InsertdrugWebResponse> InsertdrugWebAsync(string Drug_name, string Description, int Drug_price, string Drug_status) {
            pharmacufrom.ServiceReference2.InsertdrugWebRequest inValue = new pharmacufrom.ServiceReference2.InsertdrugWebRequest();
            inValue.Body = new pharmacufrom.ServiceReference2.InsertdrugWebRequestBody();
            inValue.Body.Drug_name = Drug_name;
            inValue.Body.Description = Description;
            inValue.Body.Drug_price = Drug_price;
            inValue.Body.Drug_status = Drug_status;
            return ((pharmacufrom.ServiceReference2.WebService1Soap)(this)).InsertdrugWebAsync(inValue);
        }
        
        public int InsertinventoryWeb(int Drug_id, int Quantity_in_stock, int Unit_price) {
            return base.Channel.InsertinventoryWeb(Drug_id, Quantity_in_stock, Unit_price);
        }
        
        public System.Threading.Tasks.Task<int> InsertinventoryWebAsync(int Drug_id, int Quantity_in_stock, int Unit_price) {
            return base.Channel.InsertinventoryWebAsync(Drug_id, Quantity_in_stock, Unit_price);
        }
        
        public int InsertorderWeb(int Drug_id, int Pharmacy_ID, int Quantity, int Unit_Price) {
            return base.Channel.InsertorderWeb(Drug_id, Pharmacy_ID, Quantity, Unit_Price);
        }
        
        public System.Threading.Tasks.Task<int> InsertorderWebAsync(int Drug_id, int Pharmacy_ID, int Quantity, int Unit_Price) {
            return base.Channel.InsertorderWebAsync(Drug_id, Pharmacy_ID, Quantity, Unit_Price);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pharmacufrom.ServiceReference2.InsertQuatationWebResponse pharmacufrom.ServiceReference2.WebService1Soap.InsertQuatationWeb(pharmacufrom.ServiceReference2.InsertQuatationWebRequest request) {
            return base.Channel.InsertQuatationWeb(request);
        }
        
        public int InsertQuatationWeb(string Quatation_Date, string Suppliername, int supplierid, string Status) {
            pharmacufrom.ServiceReference2.InsertQuatationWebRequest inValue = new pharmacufrom.ServiceReference2.InsertQuatationWebRequest();
            inValue.Body = new pharmacufrom.ServiceReference2.InsertQuatationWebRequestBody();
            inValue.Body.Quatation_Date = Quatation_Date;
            inValue.Body.Suppliername = Suppliername;
            inValue.Body.supplierid = supplierid;
            inValue.Body.Status = Status;
            pharmacufrom.ServiceReference2.InsertQuatationWebResponse retVal = ((pharmacufrom.ServiceReference2.WebService1Soap)(this)).InsertQuatationWeb(inValue);
            return retVal.Body.InsertQuatationWebResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pharmacufrom.ServiceReference2.InsertQuatationWebResponse> pharmacufrom.ServiceReference2.WebService1Soap.InsertQuatationWebAsync(pharmacufrom.ServiceReference2.InsertQuatationWebRequest request) {
            return base.Channel.InsertQuatationWebAsync(request);
        }
        
        public System.Threading.Tasks.Task<pharmacufrom.ServiceReference2.InsertQuatationWebResponse> InsertQuatationWebAsync(string Quatation_Date, string Suppliername, int supplierid, string Status) {
            pharmacufrom.ServiceReference2.InsertQuatationWebRequest inValue = new pharmacufrom.ServiceReference2.InsertQuatationWebRequest();
            inValue.Body = new pharmacufrom.ServiceReference2.InsertQuatationWebRequestBody();
            inValue.Body.Quatation_Date = Quatation_Date;
            inValue.Body.Suppliername = Suppliername;
            inValue.Body.supplierid = supplierid;
            inValue.Body.Status = Status;
            return ((pharmacufrom.ServiceReference2.WebService1Soap)(this)).InsertQuatationWebAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pharmacufrom.ServiceReference2.InsertquatationDetailWebResponse pharmacufrom.ServiceReference2.WebService1Soap.InsertquatationDetailWeb(pharmacufrom.ServiceReference2.InsertquatationDetailWebRequest request) {
            return base.Channel.InsertquatationDetailWeb(request);
        }
        
        public int InsertquatationDetailWeb(int Drug_id, int Quatation_Quantity, int Quatation_Unit_Price, int Quatation_ID, string Drug_name) {
            pharmacufrom.ServiceReference2.InsertquatationDetailWebRequest inValue = new pharmacufrom.ServiceReference2.InsertquatationDetailWebRequest();
            inValue.Body = new pharmacufrom.ServiceReference2.InsertquatationDetailWebRequestBody();
            inValue.Body.Drug_id = Drug_id;
            inValue.Body.Quatation_Quantity = Quatation_Quantity;
            inValue.Body.Quatation_Unit_Price = Quatation_Unit_Price;
            inValue.Body.Quatation_ID = Quatation_ID;
            inValue.Body.Drug_name = Drug_name;
            pharmacufrom.ServiceReference2.InsertquatationDetailWebResponse retVal = ((pharmacufrom.ServiceReference2.WebService1Soap)(this)).InsertquatationDetailWeb(inValue);
            return retVal.Body.InsertquatationDetailWebResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pharmacufrom.ServiceReference2.InsertquatationDetailWebResponse> pharmacufrom.ServiceReference2.WebService1Soap.InsertquatationDetailWebAsync(pharmacufrom.ServiceReference2.InsertquatationDetailWebRequest request) {
            return base.Channel.InsertquatationDetailWebAsync(request);
        }
        
        public System.Threading.Tasks.Task<pharmacufrom.ServiceReference2.InsertquatationDetailWebResponse> InsertquatationDetailWebAsync(int Drug_id, int Quatation_Quantity, int Quatation_Unit_Price, int Quatation_ID, string Drug_name) {
            pharmacufrom.ServiceReference2.InsertquatationDetailWebRequest inValue = new pharmacufrom.ServiceReference2.InsertquatationDetailWebRequest();
            inValue.Body = new pharmacufrom.ServiceReference2.InsertquatationDetailWebRequestBody();
            inValue.Body.Drug_id = Drug_id;
            inValue.Body.Quatation_Quantity = Quatation_Quantity;
            inValue.Body.Quatation_Unit_Price = Quatation_Unit_Price;
            inValue.Body.Quatation_ID = Quatation_ID;
            inValue.Body.Drug_name = Drug_name;
            return ((pharmacufrom.ServiceReference2.WebService1Soap)(this)).InsertquatationDetailWebAsync(inValue);
        }
    }
}
